name = "cf-ai-chatbot"
main = "functions/index.js"
compatibility_date = "2024-01-01"

# Bind Workers AI
[ai]
binding = "AI"

# Bind Durable Object
[[durable_objects.bindings]]
name = "CHAT_MEMORY"
class_name = "ChatMemory"
script_name = "cf-ai-simple-chatbot"

# Enable Durable Objects migration (SQLite for free tier)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatMemory"]

# Serve static assets from /public
[site]
bucket = "./public"

